import { Card, CardHeader, CardTitle, CardSubtitle, CardBody } from '@/components/ui/card';
import { useAoSoc } from '@/store/useAoSoc';
import { Progress } from '@/components/ui/progress';
import { Brain, Sparkles } from 'lucide-react';

export const AiExplanation: React.FC = () => {
  const { selectedIncident, selectedExplanation } = useAoSoc();
  const exp = selectedExplanation ?? selectedIncident?.ai_explanation;

  if (!exp) {
    return (
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Brain className="h-4 w-4 text-info" />
            <CardTitle>AI Explanation</CardTitle>
          </div>
          <CardSubtitle>Natural-language reasoning by the local LLM</CardSubtitle>
        </CardHeader>
        <CardBody>
          <div className="text-sm text-muted">Select an incident to view the LLM's assessment.</div>
        </CardBody>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-2">
          <Brain className="h-4 w-4 text-info" />
          <div>
            <CardTitle>AI Explanation</CardTitle>
            <CardSubtitle>
              Generated by <span className="text-fg">qwen2.5:14b-instruct-q5_K_M</span> via Ollama
            </CardSubtitle>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <div className="text-right">
            <div className="label">Likelihood</div>
            <div className="font-mono text-lg text-fg">{exp.likelihood}%</div>
          </div>
          <div className="w-32">
            <Progress value={exp.likelihood} tone={exp.likelihood >= 80 ? 'critical' : exp.likelihood >= 60 ? 'high' : 'medium'} />
          </div>
        </div>
      </CardHeader>
      <CardBody>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          <div className="lg:col-span-2 space-y-3">
            <div className="text-sm text-fg leading-relaxed">
              <span className="inline-flex items-center gap-1.5 text-info font-semibold mr-1">
                <Sparkles className="h-3.5 w-3.5" /> AI Assessment:
              </span>
              {exp.summary}
            </div>
            <div className="rounded-md border border-border bg-surface2/40 p-3">
              <div className="label mb-2">Evidence</div>
              <ul className="space-y-1.5 text-sm">
                {exp.bullets.map((b, i) => (
                  <li key={i} className="flex items-start gap-2 text-fg/90">
                    <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-info shrink-0" />
                    <span>{b}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="rounded-md border border-critical/30 bg-critical/5 p-4">
            <div className="label text-critical/80">Recommended Action</div>
            <div className="text-sm text-fg mt-1 leading-relaxed">
              {exp.recommendation}
            </div>
            <div className="mt-3 text-[11px] text-muted">
              Confidence in this recommendation: <span className="font-mono text-fg">{exp.likelihood}%</span>
            </div>
          </div>
        </div>
      </CardBody>
    </Card>
  );
};
